add_library(blocks_sinks INTERFACE)
add_library(cler::blocks_sinks ALIAS blocks_sinks)

add_library(blocks_sinks_core INTERFACE)
add_library(cler::blocks_sinks_core ALIAS blocks_sinks_core)
target_link_libraries(blocks_sinks_core INTERFACE cler::blocks_core)
target_include_directories(blocks_sinks_core INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})
target_link_libraries(blocks_sinks INTERFACE cler::blocks_sinks_core)

find_package(PkgConfig REQUIRED)

pkg_check_modules(PORTAUDIO portaudio-2.0)
if(PORTAUDIO_FOUND)
  message(STATUS "PortAudio found: ${PORTAUDIO_LIBRARIES}")
  add_library(blocks_sink_audio INTERFACE)
  add_library(cler::blocks_sink_audio ALIAS blocks_sink_audio)
  target_link_libraries(blocks_sink_audio INTERFACE cler::blocks_sinks_core ${PORTAUDIO_LIBRARIES})
  target_include_directories(blocks_sink_audio INTERFACE ${PORTAUDIO_INCLUDE_DIRS})
  target_compile_definitions(blocks_sink_audio INTERFACE CLER_HAS_PORTAUDIO)
  target_link_libraries(blocks_sinks INTERFACE cler::blocks_sink_audio)
  set(PORTAUDIO_FOUND ${PORTAUDIO_FOUND} CACHE INTERNAL "PortAudio found")
else()
  message(WARNING "PortAudio not found: SinkAudioBlock will not be available")
endif()

if(HACKRF_FOUND)
  target_link_libraries(blocks_sinks INTERFACE cler::blocks_hackrf)
endif()
if(UHD_FOUND)
  target_link_libraries(blocks_sinks INTERFACE cler::blocks_uhd)
endif()
if(SOAPYSDR_FOUND)
  target_link_libraries(blocks_sinks INTERFACE cler::blocks_soapysdr)
endif()
