if (CLER_BUILD_BLOCKS_GUI AND CLER_BUILD_BLOCKS_LIQUID AND HACKRF_FOUND AND PORTAUDIO_FOUND)
    add_executable(fm_radio fm_radio.cpp)
    target_link_libraries(fm_radio PRIVATE cler::desktop_blocks)
else()
    message(STATUS "Skipping fm_radio example (needs GUI + liquid + HackRF + PortAudio)")
endif()
