if (CLER_BUILD_BLOCKS_WEB)
    include(${PROJECT_SOURCE_DIR}/cmake/EmbedFiles.cmake)
    add_executable(web_demo web_demo.cpp)
    target_link_libraries(web_demo PRIVATE cler::desktop_blocks)
    cler_embed_dir(web_demo ${CMAKE_CURRENT_SOURCE_DIR}/client websdr_client_files.hpp WEBSDR_CLIENT_FILES)

    if (CLER_BUILD_BLOCKS_LIQUID)
        execute_process(COMMAND git rev-parse --short HEAD WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
                        OUTPUT_VARIABLE WEBSDR_GIT_SHA OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        string(TIMESTAMP WEBSDR_BUILD_DATE "%Y-%m-%d" UTC)
        add_executable(websdr websdr.cpp)
        target_link_libraries(websdr PRIVATE cler::desktop_blocks)
        target_compile_definitions(websdr PRIVATE WEBSDR_VERSION="${WEBSDR_GIT_SHA} ${WEBSDR_BUILD_DATE}")
        cler_embed_dir(websdr ${CMAKE_CURRENT_SOURCE_DIR}/client websdr_client_files.hpp WEBSDR_CLIENT_FILES)
    endif()
else()
    message(STATUS "Skipping websdr examples because CLER_BUILD_BLOCKS_WEB is OFF")
endif()
