if (CLER_BUILD_BLOCKS_WEB)
    include(${PROJECT_SOURCE_DIR}/cmake/EmbedFiles.cmake)
    add_executable(web_demo web_demo.cpp)
    target_link_libraries(web_demo PRIVATE cler::desktop_blocks)
    cler_embed_dir(web_demo ${CMAKE_CURRENT_SOURCE_DIR}/client websdr_client_files.hpp WEBSDR_CLIENT_FILES)

    find_program(NODE_EXECUTABLE node)
    if (NODE_EXECUTABLE AND CLER_BUILD_TESTS)
        add_test(NAME websdr_client_test COMMAND ${NODE_EXECUTABLE} --test ${CMAKE_CURRENT_SOURCE_DIR}/client_tests/proto.test.mjs ${CMAKE_CURRENT_SOURCE_DIR}/client_tests/panel.test.mjs)
    endif()
else()
    message(STATUS "Skipping websdr examples because CLER_BUILD_BLOCKS_WEB is OFF")
endif()
