execute_process(COMMAND git rev-parse --short HEAD WORKING_DIRECTORY ${SRC}
                OUTPUT_VARIABLE sha OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(NOT sha)
    set(sha unknown)
endif()
string(TIMESTAMP date "%Y-%m-%d" UTC)
set(content "#define WEBSDR_VERSION \"${sha} ${date}\"\n")
if(EXISTS ${OUT})
    file(READ ${OUT} old)
else()
    set(old "")
endif()
if(NOT content STREQUAL old)
    file(WRITE ${OUT} "${content}")
endif()
