# cross gcc must match the Pi distro (bullseye: gcc-10, e.g. debian:bullseye + crossbuild-essential-arm64); Ubuntu gcc-11 cross links against glibc 2.32 symbols
# RPI_SYSROOT: rsync -azR --copy-unsafe-links pi@host:/usr/lib :/usr/include :/usr/local/lib :/usr/local/include :/lib $RPI_SYSROOT/
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
if(DEFINED ENV{RPI_SYSROOT})
  set(RPI_SYSROOT $ENV{RPI_SYSROOT} CACHE PATH "Raspberry Pi sysroot")
endif()
if(NOT RPI_SYSROOT)
  message(FATAL_ERROR "set RPI_SYSROOT (env or -D) to a Raspberry Pi sysroot")
endif()
set(CMAKE_SYSROOT ${RPI_SYSROOT})
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES RPI_SYSROOT)
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} ${CMAKE_SYSROOT})
set(ENV{PKG_CONFIG_LIBDIR} ${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu/pkgconfig:${CMAKE_SYSROOT}/usr/lib/pkgconfig:${CMAKE_SYSROOT}/usr/share/pkgconfig:${CMAKE_SYSROOT}/usr/local/lib/pkgconfig)
set(C_HAS_NEON_1_EXITCODE 0 CACHE STRING "")
set(C_HAS_NEON_1_EXITCODE__TRYRUN_OUTPUT "" CACHE STRING "")
set(CXX_HAS_NEON_1_EXITCODE 0 CACHE STRING "")
set(CXX_HAS_NEON_1_EXITCODE__TRYRUN_OUTPUT "" CACHE STRING "")
file(GLOB _rpi_gcc_dir "${CMAKE_SYSROOT}/usr/lib/gcc/aarch64-linux-gnu/*")
set(_rpi_libs "-L${_rpi_gcc_dir} -L${CMAKE_SYSROOT}/usr/lib/aarch64-linux-gnu -L${CMAKE_SYSROOT}/lib/aarch64-linux-gnu -L${CMAKE_SYSROOT}/usr/local/lib")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_rpi_libs}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_rpi_libs}")
